name: heptapod
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - expat=2.7.3=h50f4ffc_4
  - libcxx=20.1.8=hd7fd590_1
  - libexpat=2.7.3=h50f4ffc_4
  - libffi=3.4.4=hca03da5_1
  - libmpdec=4.0.0=h80987f9_0
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.18=h9b4081a_0
  - pip=25.3=pyhc872135_0
  - python=3.13.11=hc7d8306_100_cp313
  - python_abi=3.13=3_cp313
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py313hca03da5_0
  - sqlite=3.51.0=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - wheel=0.45.1=py313hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anthropic==0.75.0
      - anyio==4.12.0
      - attrs==25.4.0
      - awkward==2.8.11
      - awkward-cpp==51
      - boto3==1.42.13
      - botocore==1.42.13
      - cachetools==6.2.4
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - distro==1.9.0
      - docstring-parser==0.17.0
      - eval-type-backport==0.3.1
      - fastapi==0.125.0
      - fonttools==4.61.1
      - fsspec==2025.12.0
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.28.1
      - google-api-python-client==2.187.0
      - google-auth==2.45.0
      - google-auth-httplib2==0.3.0
      - google-genai==1.56.0
      - google-generativeai==0.8.6
      - googleapis-common-protos==1.72.0
      - graphviz==0.21
      - groq==1.0.0
      - grpcio==1.76.0
      - grpcio-status==1.71.2
      - h11==0.16.0
      - hepunits==2.4.3
      - httpcore==1.0.9
      - httplib2==0.31.0
      - httpx==0.28.1
      - idna==3.11
      - importlib-metadata==8.7.0
      - invoke==2.2.1
      - jiter==0.12.0
      - jmespath==1.0.1
      - kiwisolver==1.4.9
      - markdown-it-py==4.0.0
      - matplotlib==3.10.8
      - mdurl==0.1.2
      - mistralai==1.10.0
      - numpy==2.3.5
      - ollama==0.6.1
      - openai==2.13.0
      - opentelemetry-api==1.38.0
      - opentelemetry-exporter-otlp-proto-common==1.38.0
      - opentelemetry-exporter-otlp-proto-http==1.38.0
      - opentelemetry-proto==1.38.0
      - opentelemetry-sdk==1.38.0
      - opentelemetry-semantic-conventions==0.59b0
      - orchestral-ai==1.2.1
      - packaging==25.0
      - pandas==2.3.3
      - particle==0.26.0
      - pexpect==4.9.0
      - pillow==12.0.0
      - proto-plus==1.27.0
      - protobuf==5.29.5
      - ptyprocess==0.7.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - pylhe==1.0.2
      - pyparsing==3.2.5
      - pythia8mc==8.316.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - requests==2.32.5
      - rich==14.2.0
      - rsa==4.9.1
      - s3transfer==0.16.0
      - scipy==1.16.3
      - six==1.17.0
      - sniffio==1.3.1
      - starlette==0.50.0
      - tenacity==9.1.2
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - uritemplate==4.2.0
      - urllib3==2.6.2
      - uvicorn==0.38.0
      - vector==1.7.0
      - websockets==15.0.1
      - zipp==3.23.0
